
server:
  port: 9001
  servlet:
    context-path: /products

spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: root
  jpa:
    hibernate:
      ddlAuto: update
    showSql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect