
server:
  port: 9002
#  servlet:
#    context-path: /orders

spring:
  application:
    name: ORDER-SERVICE
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        preferIpAddress: true
#  config:
#    import: optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: root
  jpa:
    hibernate:
      ddlAuto: update
    showSql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect